Repository Wessebanan/PA2526-Grupp-C, pull requests merged in 2019-10, with the labels that each got.

#136 Us5 holmes toggable
  AI/AI/includes/AIGlobals.h
  AI/AI/includes/GridFunctions.cpp
  AI/AI/includes/GridFunctions.h
  Game/GameMain/gameAI/AIEcsFunctions.cpp
  Game/GameMain/gameAI/GridEcsFunctions.cpp
  Game/GameMain/gameAI/GridEcsFunctions.h
  Game/GameMain/gameAI/InitGrid.h
  Lib/AI.lib
  Lib_d/AI.lib
Labels: bug, enhancement

#76 Ui decoupling maybe donno
  Game/GameMain/GameMain.vcxproj
  Game/GameMain/GameMain.vcxproj.filters
  Game/GameMain/UI/InitUI.h
  Game/GameMain/UI/UIComponents.h
  Game/GameMain/UI/UIEvents.h
  Game/GameMain/UI/UISystems.cpp
  Game/GameMain/UI/UISystems.h
  Game/GameMain/gameAI/AIEcsFunctions.cpp
  Game/GameMain/gameAI/AISystems.h
  Game/GameMain/main.cpp
  Game/GameMain_Test/GameMain_Test.vcxproj
  Game/GameMain_Test/GameMain_Test.vcxproj.filters
  Game/GameMain_Test/UI/UIEcsTest.h
  Game/GameMain_Test/test.cpp
  Graphics/includes/GraphicsInterface.h
  Graphics/source/GraphicsInterface.cpp
  Lib_d/Graphics.lib
  UI/UI.sln
  UI/UI/Direct2D.cpp
  UI/UI/Test.cpp
  UI/UI/UI.vcxproj
  UI/UI/UI.vcxproj.filters
  UI/UI/UISystems.cpp
  UI/UI/includes/Direct2D.h
  UI/UI/includes/UIComponents.h
  UI/UI/includes/UIEvents.h
  UI/UI/includes/UISystems.h
  UI/UI_test/UI_test.vcxproj
  UI/UI_test/test.cpp
Labels: invalid

#144 Us23 3 rounds auto restart
  AI/AI/includes/GridProp.h
  Game/GameMain/GameMain.vcxproj
  Game/GameMain/GameMain.vcxproj.filters
  Game/GameMain/Input/InitInterpreter.h
  Game/GameMain/Physics/InitPhysics.h
  Game/GameMain/gameAI/AIComponents.h
  Game/GameMain/gameAI/AIEcsFunctions.cpp
  Game/GameMain/gameAI/AIEcsFunctions.h
  Game/GameMain/gameAI/AISystems.h
  Game/GameMain/gameAI/InitArmy.h
  Game/GameMain/gameAI/InitGrid.h
  Game/GameMain/gameAnimation/InitAnimation.h
  Game/GameMain/gameGameLoop/GameLoopComponents.h
  Game/GameMain/gameGameLoop/GameLoopEvents.h
  Game/GameMain/gameGameLoop/GameLoopSystems.cpp
  Game/GameMain/gameGameLoop/GameLoopSystems.h
  Game/GameMain/gameGameLoop/InitGameLoop.h
  Game/GameMain/main.cpp
  InputHandler/InputHandler/scripts/script.js
Labels: enhancement

#148 🔥HOTFIX🔥_Add_Padding
  Game/GameMain/gameAI/AIEcsFunctions.cpp
Labels: Hotfix

#153 US22_Animation_Blend
  ModelLoader/ModelLoader/includes/Fbx_Loader.h
Labels: enhancement
