Repository Wessebanan/PA2526-Grupp-C, pull requests merged in 2019-11, with the labels that each got.

#242 EXTRA_Bomb_Explosion_Particles
  Game/GameMain/Physics/FightingSystem.cpp
  Game/GameMain/gameGraphics/InitParticles.h
  Game/GameMain/gameGraphics/ParticleECSComponents.h
  Game/GameMain/gameGraphics/ParticleECSSystems.cpp
  Game/GameMain/gameGraphics/ParticleECSSystems.h
  Game/GameMain/main.cpp
  Game/meshes/weapon_bomb.fbx
Labels: enhancement

#247 US21_CPU_Player_Place_Traps
  Game/GameMain/Input/InitInputBackendComponent.h
  Game/GameMain/Input/InitInputSystems.cpp
  Game/GameMain/Input/InterpretWebSystems.cpp
  Game/GameMain/gameGameLoop/GameLoopSystems.cpp
Labels: enhancement

#240 Us4 trap spawning correct
  Game/GameMain/Input/InterpretWebSystems.cpp
  Game/GameMain/gameGameLoop/GameLoopSystems.cpp
Labels: need fix

#249 Switched to 1-9 indexing instead of cordinates
  Game/GameMain/UI/InitUI.h
  Game/Sites/newSite.html
  UI/Resource/newArea50.png
Labels: hotfix
